packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@eslint/js": "9.39.2"
  "@fortawesome/fontawesome-svg-core": "^7.1.0"
  "@fortawesome/free-solid-svg-icons": "^7.1.0"
  "@fortawesome/react-fontawesome": "^3.2.0"
  "@playwright/test": "1.58.2"
  "@storybook/react": "^10.2.7"
  "@tailwindcss/postcss": "^4.1.18"
  "@testing-library/jest-dom": "^6.9.1"
  "@types/jest": "^30.0.0"
  "@types/node": "^25.2.2"
  "@types/react-dom": "^19.2.3"
  "@types/react": "^19.2.13"
  "@types/sanitize-html": "^2.16.0"
  "eslint-plugin-import-x": "^4.16.1"
  "eslint-plugin-prettier": "^5.5.5"
  "eslint-plugin-storybook": "^10.2.7"
  "eslint": "^9.39.2"
  "jest-environment-jsdom": "^30.2.0"
  "jest": "^30.2.0"
  "marked": "^17.0.1"
  "next": "^16.1.6"
  "playwright": "^1.58.2"
  "postcss": "^8.5.6"
  "react-dom": "^19.2.4"
  "react-hook-form": "7.71.1"
  "react-share": "^5.2.2"
  "react": "^19.2.4"
  "sanitize-html": "^2.17.0"
  "sharp": "^0.34.5"
  "storybook": "10.2.7"
  "tailwindcss": "^4.1.18"
  "ts-jest": "^29.4.6"
  "ts-node": "^10.9.2"
  "tsx": "^4.21.0"
  "typescript-eslint": "^8.54.0"
  "typescript": "5.9.3"
  "zod": "^4.3.6"
