import fs from 'node:fs/promises';
import path from 'node:path';
import { getLogger } from '@maw/logger';
import { Command } from 'commander';
import { type FaviconFile, type FaviconImage, favicons } from 'favicons';

import manifestConfig from '@/root/manifest.config.mjs';

const logger = getLogger().getSubLogger({
  prettyLogTemplate: '{{dateIsoStr}} {{logLevelName}} ',
  name: 'build-web-manifest',
});

const AUTO_GENERATED_WARNING = `## Important\n
This folder was generated by \`gen-manifest\` script. Do not edit it manually, as it will be overwritten on the next run.`;

const program = new Command();

program
  .name('build-web-manifest')
  .description('Generate web manifest and favicons')
  .option(
    '-s, --source <path>',
    'Favicon source image path',
    './public/assets/appicon.png',
  )
  .option(
    '-o, --output-dir <path>',
    'Output directory for favicons',
    './public/',
  )
  .parse(process.argv);

const options = program.opts();

const main = async () => {
  logger.info('🔄 Generating manifest...');

  const faviconSource = options.source;
  const manifestDestPath = path.join(
    options.outputDir,
    `${manifestConfig.path}`,
  );

  logger.info(`Generating favicons from ${faviconSource}`);
  const response = await favicons(faviconSource, manifestConfig);

  logger.info(`Writing images into ${manifestDestPath}`);
  await storeFiles(manifestDestPath, response.images);

  logger.info(`Moving favicon into public root`);
  await fs.copyFile(
    path.join(manifestDestPath, 'favicon.ico'),
    path.join(options.outputDir, 'favicon.ico'),
  );
  await fs.rm(path.join(manifestDestPath, 'favicon.ico'));

  logger.info(`Writing manifest into ${manifestDestPath}`);
  await storeFiles(manifestDestPath, response.files);
};

const storeFiles = async (
  targetPath: string,
  files: FaviconImage[] | FaviconFile[],
) => {
  await fs.mkdir(targetPath, { recursive: true });
  await fs.writeFile(
    path.join(targetPath, 'README.md'),
    AUTO_GENERATED_WARNING,
  );
  await Promise.all(
    files.map(
      async (file) =>
        await fs.writeFile(
          path.join(targetPath, file.name),
          sanitizeContent(file.name, file.contents),
        ),
    ),
  );
};

const sanitizeContent = (filename: string, content: string | Buffer) => {
  if (filename !== 'manifest.webmanifest') {
    return content;
  }

  // For Biome compatibility, we need to sure that this file generated by 3rd party does in fact has a tailing new line.
  const readContent = content.toString();
  if (readContent.endsWith('\n')) {
    return readContent;
  }
  return `${readContent}\n`;
};

main()
  .then(() => logger.info(`✅ Aaaaand it's done. New manifest created.`))
  .catch((err) => {
    logger.error(err, `Ooopsie, something went wrong.`);
    process.exit(1);
  });
