import favicons, { type FaviconFile, type FaviconImage } from 'favicons';
import fs from 'fs/promises';
import path from 'path';

import manifestConfig from '@/root/manifest.config.mjs';

const main = async () => {
  const faviconSource = './public/assets/appicon.png';
  const manifestDestPath = path.join('./public/', manifestConfig.path!);

  console.log(`Generating favicons from ${faviconSource}`);
  const response = await favicons(faviconSource, manifestConfig);

  console.log(`Writing images into ${manifestDestPath}`);
  await storeFiles(manifestDestPath, response.images);

  console.log(`Moving favicon into public root`);
  await fs.copyFile(
    path.join(manifestDestPath, 'favicon.ico'),
    './public/favicon.ico',
  );
  await fs.rm(path.join(manifestDestPath, 'favicon.ico'));

  console.log(`Writing manifest into ${manifestDestPath}`);
  await storeFiles(manifestDestPath, response.files);
};

const autoGeneratedWarning = `## Important\n
This folder was generated by \`gen-manifest\` script. Do not edit it manually, as it will be overwritten on the next run.`;

const storeFiles = async (
  targetPath: string,
  files: FaviconImage[] | FaviconFile[],
) => {
  await fs.mkdir(targetPath, { recursive: true });
  await fs.writeFile(path.join(targetPath, 'README.md'), autoGeneratedWarning);
  await Promise.all(
    files.map(
      async (file) =>
        await fs.writeFile(path.join(targetPath, file.name), file.contents),
    ),
  );
};

console.log('Generating manifest...');
main()
  .then(() => console.log(`Aaaaand it's done. New manifest created.\n`))
  .catch((err) => console.error(`Ooopsie, something went wrong: ${err}`));
