import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRoot = path.resolve(__dirname, '..');

const DEFAULT_URL = 'https://content.themostannoyingwebsite.com/docs/json';
const DEFAULT_SPEC_PATH = path.join(packageRoot, 'spec', 'openapi.json');
const DEFAULT_OUTPUT_DIR = path.join(packageRoot, 'src', 'generated');

interface CliOptions {
  url: string;
  specPath: string;
  outputDir: string;
  noFetch: boolean;
}

function parseArgs(): CliOptions {
  const args = process.argv.slice(2);
  const options: CliOptions = {
    url: process.env.CONTENT_API_SPEC_URL || DEFAULT_URL,
    specPath: DEFAULT_SPEC_PATH,
    outputDir: DEFAULT_OUTPUT_DIR,
    noFetch: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--url' && args[i + 1]) {
      options.url = args[++i];
    } else if (arg === '--spec' && args[i + 1]) {
      options.specPath = path.resolve(process.cwd(), args[++i]);
    } else if (arg === '--output' && args[i + 1]) {
      options.outputDir = path.resolve(process.cwd(), args[++i]);
    } else if (arg === '--no-fetch') {
      options.noFetch = true;
    }
  }

  return options;
}

async function fetchOrReadSpec(options: CliOptions): Promise<OpenAPI3> {
  let specJson: string | null = null;

  if (!options.noFetch) {
    try {
      console.log(`🌐 Fetching OpenAPI spec from ${options.url}...`);
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000);
      const res = await fetch(options.url, {
        headers: { Accept: 'application/json' },
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      if (!res.ok) {
        throw new Error(`HTTP error ${res.status}: ${res.statusText}`);
      }

      specJson = await res.text();
      const parsed = JSON.parse(specJson);
      fs.mkdirSync(path.dirname(options.specPath), { recursive: true });
      fs.writeFileSync(
        options.specPath,
        JSON.stringify(parsed, null, 2),
        'utf-8',
      );
      console.log(`💾 Saved cached OpenAPI spec to ${options.specPath}`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`⚠️  Failed to fetch from ${options.url}: ${msg}`);
    }
  }

  if (!specJson) {
    if (fs.existsSync(options.specPath)) {
      console.log(`📂 Using existing cached spec at ${options.specPath}`);
      specJson = fs.readFileSync(options.specPath, 'utf-8');
    } else {
      throw new Error(
        `Unable to fetch spec and no cached file found at ${options.specPath}`,
      );
    }
  }

  return JSON.parse(specJson) as OpenAPI3;
}

function generateSchemasCode(): string {
  return `/**
 * This file was auto-generated by the swagger generator task.
 * Do not make direct manual changes.
 */

import { z } from 'zod';

/* ==========================================================================
 * Common Domain Models
 * ========================================================================== */

/** Supported ISO language codes */
export const LanguageSchema = z.enum([
  'ar',
  'de',
  'en',
  'es',
  'fr',
  'hi',
  'hu',
  'it',
  'ja',
  'ko',
  'pl',
  'pt',
  'ru',
  'tr',
  'zh',
]);

/** Image variant metadata containing transformed URL, dimensions, and format */
export const ImageVariantSchema = z
  .object({
    url: z.string().describe('Publicly accessible URL to the image variant'),
    width: z.number().describe('Width in pixels'),
    height: z.number().describe('Height in pixels'),
    format: z.string().describe('Image file format (e.g. webp)'),
    file_size_bytes: z.number().optional().describe('File size in bytes'),
  })
  .strict()
  .describe('Single image variant metadata');

/** Responsive map of image variants indexed by breakpoint name (e.g. sm, lg) */
export const ImageVariantsMapSchema = z
  .record(z.string(), ImageVariantSchema)
  .describe('Responsive image variants map (e.g. sm, lg)');

/** Featured image asset metadata with responsive variants, or null if unset */
export const FeaturedImageSchema = z
  .union([
    z
      .object({
        name: z.string().describe('Original image asset base name'),
        variants: ImageVariantsMapSchema,
      })
      .strict(),
    z.null(),
  ])
  .describe('Featured image asset with responsive variants');

/** Localized article item representation */
export const ArticleItemSchema = z
  .object({
    id: z.string().describe('Deterministic UUID v5 identifier'),
    article_group: z.string().describe('Canonical article group identifier'),
    slug: z.string().describe('Localized article slug identifier'),
    lang: LanguageSchema.describe('ISO language code'),
    title: z.string().describe('Article title'),
    summary: z.string().describe('Short article summary'),
    content: z.string().describe('Full article Markdown content'),
    author: z.string().describe('Article author'),
    published_at: z.string().describe('ISO publication timestamp'),
    reading_time_minutes: z
      .number()
      .describe('Estimated reading time in minutes'),
    is_featured: z.boolean().describe('Featured/cover article flag'),
    featured_image: FeaturedImageSchema,
    tags: z.array(z.string()).describe('List of article tags'),
    keywords: z.array(z.string()).describe('List of article search keywords'),
  })
  .strict()
  .describe('Localized article item');

/** Translation reference pointing to an article translation */
export const ArticleTranslationSchema = z
  .object({
    lang: LanguageSchema.describe('ISO language code'),
    slug: z.string().describe('Localized article slug identifier'),
    title: z.string().describe('Article title'),
  })
  .strict()
  .describe('Available alternative translation for an article');

/** Detailed article item including available alternative translations */
export const ArticleDetailSchema = ArticleItemSchema.extend({
  translations: z
    .array(ArticleTranslationSchema)
    .describe('Available alternative translations for this article'),
})
  .strict()
  .describe('Article item with available alternative translations');

/** Localized static page item representation */
export const PageItemSchema = z
  .object({
    id: z.string().describe('Deterministic UUID v5 identifier'),
    page_group: z.string().describe('Canonical page group identifier'),
    slug: z.string().describe('Localized page slug identifier'),
    lang: LanguageSchema.describe('ISO language code'),
    title: z.string().describe('Page title'),
    summary: z
      .string()
      .nullable()
      .describe('Short page summary or meta description'),
    content: z.string().describe('Full page Markdown content'),
    author: z.string().nullable().describe('Page author'),
    published_at: z
      .string()
      .nullable()
      .describe('ISO publication timestamp'),
    reading_time_minutes: z
      .number()
      .describe('Estimated reading time in minutes'),
    created_at: z.string().describe('ISO creation timestamp'),
    updated_at: z.string().describe('ISO update timestamp'),
  })
  .strict()
  .describe('Localized static page item');

/** Translation reference pointing to a static page translation */
export const PageTranslationSchema = z
  .object({
    lang: LanguageSchema.describe('ISO language code'),
    slug: z.string().describe('Localized page slug identifier'),
    title: z.string().describe('Page title'),
  })
  .strict()
  .describe('Available alternative translation for a static page');

/** Detailed static page item including available alternative translations */
export const PageDetailSchema = PageItemSchema.extend({
  translations: z
    .array(PageTranslationSchema)
    .describe('Available alternative translations for this page'),
})
  .strict()
  .describe('Static page item with available alternative translations');

/** Taxonomy tag item with localized usage count */
export const TagTaxonomyItemSchema = z
  .object({
    tag: z.string().describe('Tag name'),
    lang: LanguageSchema.describe('ISO language code of tag'),
    count: z.number().describe('Number of articles associated with this tag'),
  })
  .strict()
  .describe('Tag taxonomy item');

/** Transformed raster image asset representation */
export const ImageAssetItemSchema = z
  .object({
    name: z.string().describe('Original image asset base name'),
    variants: ImageVariantsMapSchema,
  })
  .strict()
  .describe('Transformed raster image asset and responsive variants');

/** API service health and database connection status */
export const HealthResponseSchema = z
  .object({
    status: z.string().describe('Status indicator (e.g. ok)'),
    version: z.string().describe('API version string (1.0.0)'),
    database: z.string().describe('Database connection status (e.g. connected)'),
    timestamp: z.string().describe('ISO timestamp of health response'),
  })
  .describe('System health check response');

/* ==========================================================================
 * Error Schemas
 * ========================================================================== */

/** Standardized bad request / validation error */
export const ValidationErrorSchema = z
  .object({
    code: z.literal('VALIDATION_ERROR').describe('Standardized validation error code'),
    error: z.string().describe('Validation error explanation'),
    message: z.string().optional().describe('Detailed validation error information'),
  })
  .describe('Validation error response');

/** Standardized resource not found error */
export const NotFoundErrorSchema = z
  .object({
    code: z.literal('NOT_FOUND').describe('Standardized resource not found error code'),
    error: z.string().describe('Not found error explanation'),
    message: z.string().describe('Not found message'),
  })
  .describe('Resource not found response');

/** Standardized internal server error */
export const InternalServerErrorSchema = z
  .object({
    code: z.literal('INTERNAL_SERVER_ERROR').describe('Standardized internal server error code'),
    error: z.string().describe('Internal error explanation'),
    message: z.string().optional().describe('Optional error message'),
  })
  .describe('Internal server error response');

/* ==========================================================================
 * Request Query & Parameter Schemas
 * ========================================================================== */

/** Query parameters for GET /api/v1/articles */
export const GetArticlesQuerySchema = z.object({
  lang: LanguageSchema.optional().describe('ISO language code'),
  limit: z
    .number()
    .min(1)
    .max(100)
    .default(20)
    .optional()
    .describe('Max number of items (default 20, max 100)'),
  offset: z
    .number()
    .min(0)
    .default(0)
    .optional()
    .describe('Pagination offset (default 0)'),
  q: z
    .string()
    .optional()
    .describe('Search query string (matches title, summary, or content)'),
  tag: z.string().optional().describe('Filter by tag'),
  is_featured: z
    .boolean()
    .optional()
    .describe('Filter by cover/featured status (true or false)'),
});

/** Path and query parameters for GET /api/v1/articles/{slug} */
export const GetArticleBySlugParamsSchema = z.object({
  slug: z.string().describe('Article slug identifier'),
  lang: LanguageSchema.optional().describe('ISO language code'),
});

/** Query parameters for GET /api/v1/pages */
export const GetPagesQuerySchema = z.object({
  lang: LanguageSchema.optional().describe('ISO language code'),
  limit: z
    .number()
    .min(1)
    .max(100)
    .default(20)
    .optional()
    .describe('Max number of items (default 20, max 100)'),
  offset: z
    .number()
    .min(0)
    .default(0)
    .optional()
    .describe('Pagination offset (default 0)'),
  q: z
    .string()
    .optional()
    .describe('Search query string (matches title, summary, or content)'),
});

/** Path and query parameters for GET /api/v1/pages/{slug} */
export const GetPageBySlugParamsSchema = z.object({
  slug: z.string().describe('Page slug identifier'),
  lang: LanguageSchema.optional().describe('ISO language code'),
});

/** Query parameters for GET /api/v1/tags */
export const GetTagsQuerySchema = z.object({
  lang: LanguageSchema.optional().describe('ISO language code'),
  limit: z
    .number()
    .min(1)
    .max(100)
    .default(20)
    .optional()
    .describe('Max number of items (default 20, max 100)'),
  offset: z
    .number()
    .min(0)
    .default(0)
    .optional()
    .describe('Pagination offset (default 0)'),
});

/** Query parameters for GET /api/v1/images */
export const GetImagesQuerySchema = z.object({
  limit: z
    .number()
    .min(1)
    .max(100)
    .default(20)
    .optional()
    .describe('Max number of items (default 20, max 100)'),
  offset: z
    .number()
    .min(0)
    .default(0)
    .optional()
    .describe('Pagination offset (default 0)'),
});

/* ==========================================================================
 * Paginated & Endpoint Response Schemas
 * ========================================================================== */

/** Paginated articles response schema */
export const GetArticlesResponseSchema = z
  .object({
    total: z.number().describe('Total count of items matching the query'),
    limit: z.number().describe('Max number of items per page'),
    offset: z.number().describe('Offset number of items skipped'),
    items: z.array(ArticleItemSchema).describe('Paginated list of localized articles'),
  })
  .strict()
  .describe('Paginated list of localized articles');

/** Single article with translations response schema */
export const GetArticleBySlugResponseSchema = ArticleDetailSchema;

/** Paginated static pages response schema */
export const GetPagesResponseSchema = z
  .object({
    total: z.number().describe('Total count of items matching the query'),
    limit: z.number().describe('Max number of items per page'),
    offset: z.number().describe('Offset number of items skipped'),
    items: z.array(PageItemSchema).describe('Paginated list of localized static pages'),
  })
  .strict()
  .describe('Paginated list of localized static pages');

/** Single static page with translations response schema */
export const GetPageBySlugResponseSchema = PageDetailSchema;

/** Paginated taxonomy tags response schema */
export const GetTagsResponseSchema = z
  .object({
    total: z.number().describe('Total count of items matching the query'),
    limit: z.number().describe('Max number of items per page'),
    offset: z.number().describe('Offset number of items skipped'),
    items: z.array(TagTaxonomyItemSchema).describe('Paginated list of tag taxonomy items'),
  })
  .strict()
  .describe('Paginated list of tag taxonomy items');

/** Paginated image assets response schema */
export const GetImagesResponseSchema = z
  .object({
    total: z.number().describe('Total count of items matching the query'),
    limit: z.number().describe('Max number of items per page'),
    offset: z.number().describe('Offset number of items skipped'),
    items: z.array(ImageAssetItemSchema).describe('Paginated list of transformed raster image assets and metadata'),
  })
  .strict()
  .describe('Paginated list of transformed raster image assets and metadata');

/** Health check response schema */
export const GetHealthResponseSchema = HealthResponseSchema;
`;
}

function generateTypesCode(): string {
  return `/**
 * This file was auto-generated by the swagger generator task.
 * Do not make direct manual changes.
 */

import type { z } from 'zod';
import type {
  ArticleDetailSchema,
  ArticleItemSchema,
  ArticleTranslationSchema,
  FeaturedImageSchema,
  GetArticleBySlugParamsSchema,
  GetArticleBySlugResponseSchema,
  GetArticlesQuerySchema,
  GetArticlesResponseSchema,
  GetHealthResponseSchema,
  GetImagesQuerySchema,
  GetImagesResponseSchema,
  GetPageBySlugParamsSchema,
  GetPageBySlugResponseSchema,
  GetPagesQuerySchema,
  GetPagesResponseSchema,
  GetTagsQuerySchema,
  GetTagsResponseSchema,
  HealthResponseSchema,
  ImageAssetItemSchema,
  ImageVariantSchema,
  ImageVariantsMapSchema,
  InternalServerErrorSchema,
  LanguageSchema,
  NotFoundErrorSchema,
  PageDetailSchema,
  PageItemSchema,
  PageTranslationSchema,
  TagTaxonomyItemSchema,
  ValidationErrorSchema,
} from './schemas.js';

/* ==========================================================================
 * Domain Inferred Types
 * ========================================================================== */

export type Language = z.infer<typeof LanguageSchema>;
export type ImageVariant = z.infer<typeof ImageVariantSchema>;
export type ImageVariantsMap = z.infer<typeof ImageVariantsMapSchema>;
export type FeaturedImage = z.infer<typeof FeaturedImageSchema>;
export type ArticleItem = z.infer<typeof ArticleItemSchema>;
export type ArticleTranslation = z.infer<typeof ArticleTranslationSchema>;
export type ArticleDetail = z.infer<typeof ArticleDetailSchema>;
export type PageItem = z.infer<typeof PageItemSchema>;
export type PageTranslation = z.infer<typeof PageTranslationSchema>;
export type PageDetail = z.infer<typeof PageDetailSchema>;
export type TagTaxonomyItem = z.infer<typeof TagTaxonomyItemSchema>;
export type ImageAssetItem = z.infer<typeof ImageAssetItemSchema>;
export type HealthResponse = z.infer<typeof HealthResponseSchema>;

/* ==========================================================================
 * Error Inferred Types
 * ========================================================================== */

export type ValidationError = z.infer<typeof ValidationErrorSchema>;
export type NotFoundError = z.infer<typeof NotFoundErrorSchema>;
export type InternalServerError = z.infer<typeof InternalServerErrorSchema>;

/* ==========================================================================
 * Request Parameter & Query Types
 * ========================================================================== */

export type GetArticlesQuery = z.infer<typeof GetArticlesQuerySchema>;
export type GetArticleBySlugParams = z.infer<typeof GetArticleBySlugParamsSchema>;
export type GetPagesQuery = z.infer<typeof GetPagesQuerySchema>;
export type GetPageBySlugParams = z.infer<typeof GetPageBySlugParamsSchema>;
export type GetTagsQuery = z.infer<typeof GetTagsQuerySchema>;
export type GetImagesQuery = z.infer<typeof GetImagesQuerySchema>;

/* ==========================================================================
 * Endpoint Response Types
 * ========================================================================== */

export type GetArticlesResponse = z.infer<typeof GetArticlesResponseSchema>;
export type GetArticleBySlugResponse = z.infer<typeof GetArticleBySlugResponseSchema>;
export type GetPagesResponse = z.infer<typeof GetPagesResponseSchema>;
export type GetPageBySlugResponse = z.infer<typeof GetPageBySlugResponseSchema>;
export type GetTagsResponse = z.infer<typeof GetTagsResponseSchema>;
export type GetImagesResponse = z.infer<typeof GetImagesResponseSchema>;
export type GetHealthResponse = z.infer<typeof GetHealthResponseSchema>;

/* ==========================================================================
 * Re-export Raw OpenAPI Contract Types
 * ========================================================================== */

export type * from './openapi.js';
`;
}

function generateEndpointsCode(): string {
  return `/**
 * This file was auto-generated by the swagger generator task.
 * Do not make direct manual changes.
 */

import {
  GetArticleBySlugParamsSchema,
  GetArticleBySlugResponseSchema,
  GetArticlesQuerySchema,
  GetArticlesResponseSchema,
  GetHealthResponseSchema,
  GetImagesQuerySchema,
  GetImagesResponseSchema,
  GetPageBySlugParamsSchema,
  GetPageBySlugResponseSchema,
  GetPagesQuerySchema,
  GetPagesResponseSchema,
  GetTagsQuerySchema,
  GetTagsResponseSchema,
  InternalServerErrorSchema,
  NotFoundErrorSchema,
  ValidationErrorSchema,
} from './schemas.js';

/**
 * Metadata descriptor for content service endpoints.
 */
export const ENDPOINTS = {
  health: {
    path: '/health',
    method: 'GET',
    summary: 'System health check and database connection status',
    responseSchema: GetHealthResponseSchema,
    errorSchemas: {
      500: InternalServerErrorSchema,
    },
  },
  apiV1Health: {
    path: '/api/v1/health',
    method: 'GET',
    summary: 'System health check and database connection status',
    responseSchema: GetHealthResponseSchema,
    errorSchemas: {
      500: InternalServerErrorSchema,
    },
  },
  getArticles: {
    path: '/api/v1/articles',
    method: 'GET',
    summary: 'Get localized articles list',
    querySchema: GetArticlesQuerySchema,
    responseSchema: GetArticlesResponseSchema,
    errorSchemas: {
      400: ValidationErrorSchema,
      500: InternalServerErrorSchema,
    },
  },
  getArticleBySlug: {
    path: '/api/v1/articles/{slug}',
    method: 'GET',
    summary: 'Get article by slug with optional translation filter',
    paramsSchema: GetArticleBySlugParamsSchema,
    responseSchema: GetArticleBySlugResponseSchema,
    errorSchemas: {
      400: ValidationErrorSchema,
      404: NotFoundErrorSchema,
      500: InternalServerErrorSchema,
    },
  },
  getPages: {
    path: '/api/v1/pages',
    method: 'GET',
    summary: 'Get localized static pages list',
    querySchema: GetPagesQuerySchema,
    responseSchema: GetPagesResponseSchema,
    errorSchemas: {
      400: ValidationErrorSchema,
      500: InternalServerErrorSchema,
    },
  },
  getPageBySlug: {
    path: '/api/v1/pages/{slug}',
    method: 'GET',
    summary: 'Get static page by slug with optional translation filter',
    paramsSchema: GetPageBySlugParamsSchema,
    responseSchema: GetPageBySlugResponseSchema,
    errorSchemas: {
      400: ValidationErrorSchema,
      404: NotFoundErrorSchema,
      500: InternalServerErrorSchema,
    },
  },
  getTags: {
    path: '/api/v1/tags',
    method: 'GET',
    summary: 'Get paginated article tag taxonomy',
    querySchema: GetTagsQuerySchema,
    responseSchema: GetTagsResponseSchema,
    errorSchemas: {
      400: ValidationErrorSchema,
      500: InternalServerErrorSchema,
    },
  },
  getImages: {
    path: '/api/v1/images',
    method: 'GET',
    summary: 'Get paginated list of transformed raster image assets and metadata',
    querySchema: GetImagesQuerySchema,
    responseSchema: GetImagesResponseSchema,
    errorSchemas: {
      400: ValidationErrorSchema,
      500: InternalServerErrorSchema,
    },
  },
} as const;

export type EndpointName = keyof typeof ENDPOINTS;
`;
}

function generateGeneratedIndexCode(): string {
  return `/**
 * This file was auto-generated by the swagger generator task.
 * Do not make direct manual changes.
 */

export * from './schemas.js';
export * from './types.js';
export * from './endpoints.js';
export type * from './openapi.js';
`;
}

async function main() {
  const options = parseArgs();
  console.log('🚀 Starting content-sdk Swagger Generator...');

  const spec = await fetchOrReadSpec(options);
  fs.mkdirSync(options.outputDir, { recursive: true });

  // 1. Generate TypeScript definitions from OpenAPI spec using openapi-typescript
  console.log('📝 Generating OpenAPI TypeScript types...');
  const ast = await openapiTS(spec);
  const openapiTypesCode = astToString(ast);
  fs.writeFileSync(
    path.join(options.outputDir, 'openapi.ts'),
    `/**\n * Auto-generated by openapi-typescript from OpenAPI spec.\n * Do not edit manually.\n */\n\n${openapiTypesCode}\n`,
    'utf-8',
  );

  // 2. Generate Zod schemas
  console.log('⚡ Generating Zod schemas...');
  const schemasCode = generateSchemasCode();
  fs.writeFileSync(
    path.join(options.outputDir, 'schemas.ts'),
    schemasCode,
    'utf-8',
  );

  // 3. Generate Inferred Types
  console.log('🏷️  Generating inferred TypeScript types...');
  const typesCode = generateTypesCode();
  fs.writeFileSync(
    path.join(options.outputDir, 'types.ts'),
    typesCode,
    'utf-8',
  );

  // 4. Generate Endpoints Metadata
  console.log('🗺️  Generating endpoints descriptors...');
  const endpointsCode = generateEndpointsCode();
  fs.writeFileSync(
    path.join(options.outputDir, 'endpoints.ts'),
    endpointsCode,
    'utf-8',
  );

  // 5. Generate Generated Index
  fs.writeFileSync(
    path.join(options.outputDir, 'index.ts'),
    generateGeneratedIndexCode(),
    'utf-8',
  );

  // 6. Format generated files using Biome
  try {
    console.log('✨ Formatting generated files with Biome...');
    execSync('pnpm biome check --write --no-errors-on-unmatched .', {
      cwd: packageRoot,
      stdio: 'pipe',
    });
  } catch (_e) {
    // Ignore formatting warnings if biome check exits with non-zero due to hints
  }

  console.log('✅ Swagger generation completed successfully!');
}

main().catch((err) => {
  console.error('❌ Swagger generation failed:', err);
  process.exit(1);
});
