# Retreives the list of Github
# gh api graphql -f owner='onetdev' -f name='themostannoyingwebsite.com' -F query=@.github/queries/security-report-open.gql
query RepositoryVulnerabilities($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    vulnerabilityAlerts(first: 100, states: [OPEN]) {
      nodes {
        securityVulnerability {
          advisory {
            ghsaId
            summary
            identifiers {
              type
              value
            }
          }
          package {
            name
          }
          severity
        }
      }
    }
  }
}
