name: Playwright Tests
on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      testMatch:
        description: 'Test match pattern with regex support'
        required: false
        default: ''

jobs:
  web-test:
    name: Playwright Tests for Web
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Build the project
      run: pnpm run build --filter='!@maw/ui-docs'
    - name: Install Playwright Browsers
      run: pnpm --filter '@maw/web' exec playwright install --with-deps
    - name: Run Playwright tests for Web
      run: |
          TEST_MATCH="${{ github.event.inputs.testMatch }}"
          if [ -n "$TEST_MATCH" ]; then
            pnpm --filter '@maw/web' run test:e2e -- "$TEST_MATCH"
          else
            pnpm --filter '@maw/web' run test:e2e
          fi
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: apps/web/playwright-report/
        retention-days: 30
