name: PR clerk

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  merge_group:

concurrency:
  group: pr-clerk-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  author-as-assignee:
    name: Author as assignee
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto-assign.yml

  validate-pr-title:
    name: Validate PR title
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: Labeling PR
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
